export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR';

export const SET_PARAMETER = 'SET_PARAMETER';
export const SET_VALUE = 'SET_VALUE';
export const SET_SORT_METHOD = 'SET_SORT_METHOD';
export const SORT_RESULTS = 'SORT_RESULTS';

export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';
export const GET_MOVIES_WITH_CO_SUCCESS = 'GET_MOVIES_WITH_CO_SUCCESS';
export const GET_MOVIES_WITH_CO_ERROR = 'GET_MOVIES_WITH_CO_ERROR';